Issue 32
w3c/dx-connegp pull request #48
Opened 2023-08-23 11:58 UTC by nicholascar

Address #32

2023-09-06 11:16 UTC, rob-metalinkage approved these changes

2023-09-06 14:01 UTC, larsgsvensson requested changes
In [#32](https://github.com/w3c/dx-connegp/issues/32#issuecomment-1689781855) it says that we should "create a namespaces table in the document preamble". If interpret the html correctly, this table is still missing (or am I missing something)?

2023-09-06 20:35 UTC, nicholascar commented
You are correct Lars, and that's why I created this as a Draft PR - that it still not done. But then I forgot about that bit in the meeting just now and converted the PR from Draft to ready. I will update this PR with that change shortly.

2023-09-07 10:03 UTC, larsgsvensson commented
> You are correct Lars, and that's why I created this as a Draft PR - that it still not done. But then I forgot about that bit in the meeting just now and converted the PR from Draft to ready. I will update this PR with that change shortly.

OK, thx. Looking forward to that.

2023-09-07 12:39 UTC, nicholascar commented
Namespaces table added.

I tidied up Turtle to use `PREFIX` consistently, not some `PREFIX` and some `@prefix`.

Replaces one different use of `altr` in an example.

2023-09-07 15:23 UTC, YoucTagh requested changes
[Example 17](https://w3c.github.io/dx-connegp/connegp/#eg-html-altp) uses `rdfs:Resource` while the rest of the document uses `rdfs:Resource`.

I noticed that `CODE LISTING 3` is overflowing. Maybe because it is missing a css style class.

2023-09-24 11:53 UTC, nicholascar commented
All `rdf:Resource` mistakes have been converted to correct `rdfs:Resource`

2023-09-25 08:34 UTC, YoucTagh requested changes
In `index.html` line 1523 `rdfs:Resource` is used, while in the rest `rdfs:Resources` is the one used.

2023-10-01 16:16 UTC, rob-metalinkage reviewed
There is a lot of changes here - would be good to document what and why - using a formatting tool to normalise is obviously a good thing.  it looks like only one substantive fix ?

2024-02-07 02:39 UTC, nicholascar commented
I've fixed the mistaken plural `rdfs:Resources` and updated it to `rdfs:Resource`.

I've merged in all the other elements here too, such as Yousuf's editor details.

2024-02-07 09:43 UTC, YoucTagh approved these changes
Everything looks good to me. Thanks!

2024-02-07 11:05 UTC, merged