address issue #58
w3c/dx-connegp pull request #60
Opened 2023-11-01 08:08 UTC by YoucTagh

2023-11-01 08:14 UTC, larsgsvensson requested changes

2023-11-01 08:14 UTC, larsgsvensson commented on connegp-implementation-report/config.js
> +            href: "https://datatracker.ietf.org/doc/draft-svensson-profiled-representations/01/",
I'd say it's better to point to the github version of the I-D until we've clarified with IETF if we can have it accepted by an IETF WG. The github version is the most recent one.

2023-11-27 17:04 UTC, larsgsvensson approved these changes

2023-12-13 12:29 UTC, rob-metalinkage approved these changes

2023-12-13 12:33 UTC, pchampin approved these changes

2023-12-13 12:34 UTC, merged